# Project: lab1
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Program.o qtest.o
LINKOBJ  = main.o Program.o qtest.o
LIBS     = -L"C:/util/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/util/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/util/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Lab1_proc.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11 -g3
CFLAGS   = $(INCS) -std=gnu++11 -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Program.o: Program.cpp
	$(CPP) -c Program.cpp -o Program.o $(CXXFLAGS)

qtest.o: qtest.cpp
	$(CPP) -c qtest.cpp -o qtest.o $(CXXFLAGS)
